### ISSUE TITLE
Weird binary file, library wasn't able to give any output

### ISSUE THREAD

**Issue by mahmoudaljan** [receipt-print-hq/escpos-tools#50]
The captured a receipt's binary bellow:
[receipt.log](https://github.com/receipt-print-hq/escpos-tools/files/2239346/receipt.log)
does not seem to play nice with the library. The printer is Rongta-RP80 on windows

Printing the included sample bin file yeilded this : 

![20180730_012455](https://user-images.githubusercontent.com/26923780/43372329-95bff87e-9397-11e8-80bd-2f5e490ef1fa.jpg)

Thank you for your help.

**Comment by mike42** [comment]
Thanks for attaching the file. You found an image command which I hadn't finished implementing yet, please pull the latest code and try again, looks good to me now (there is no text in this receipt, just pictures, [see this blog post](https://mike42.me/blog/2018-05-recovering-text-from-a-receipt-with-escpos-tools) for how to recover text from this via OCR).

```bash
$ esc2html receipt.log > receipt.html
```

![image](https://user-images.githubusercontent.com/2080552/43454930-c4d18d10-9501-11e8-99f2-7b68603222f9.png)

As for your print-out, that's just some test input to run through the command-line tools. It doesn't really matter whether you can print it (it will only work on Epson printers because of the image format used), the point is that `esc2html` can understand it :)
